version: '3.7'

services:
  redis:
    image: 'redis'
    ports:
      - '6379:6379'

  mongo:
    image: 'mongo:latest'
    ports:
      - '27017:27017'

  api:
    build: .
    ports:
      - '3000:3011'
    depends_on:
      - 'mongo'
      - 'redis'
